### ISSUE TITLE
librpmio.so.9 needed by libappstream-glib

### ISSUE THREAD

**Issue by megamaced** [sailfishos-flatpak/flatpak-runner#26]
Hi

Trying to install flatpak-runner on Sailfish 4.2.0.21

Get unsatisfied dependency librpmio.so.9 needed by libappstream-glib

My lib folder has librpmio.so.8. Does flatpak runner require a newer SailfishOS?

Thanks

**Comment by rinigus** [comment]
As OBS switched to 4.3.0.12 by default, then Flatpak got rebuilt. I don't use it myself as it doesn't work on aarch64 for me, so don't follow it much either. Maybe it will change in future, but hard to tell if and when. So, if you need builds for other SFOS versions, consider building them at OBS

I probably should push flatpak support to Chum, but that requires some testing which I am not able to do.
