### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by Matias314** [sailfishos-flatpak/flatpak-runner#28]
Hello, I uninstalled flatpak-runner and want to reinstall it. However it returns a package not found. I still have your repo added/enabled and already tried another pkcon refresh without luck.

**Comment by rinigus** [comment]
Hard to say what's a reason - it is available at https://build.sailfishos.org/project/show/home:rinigus:flatpak . So, try to install in terminal and see what's error message. 

Note that for aarch64 I couldn't get it working. As I don't have any 32bit device, I haven't checked on whether it works these days.

**Comment by Matias314** [comment]
Ahh I see. Yeah it's not gonna work then, thanks for the clarification.
