### ISSUE TITLE
Add integration with Lipstick app drawer

### ISSUE THREAD

**Issue by rinigus** [sailfishos-flatpak/flatpak-runner#8]
Either via script or inside main `flatpak-runner` program, add ability to sync list of installed applications with Lipstick app drawer.

**Comment by piggz** [comment]
This is a script ive created
flatpak list --app --columns=name,description,application | while read -r line ; do
    IFS=$':' APP=(${line//$'\t'/:})       # Replace tabs with colons.
 
    DESKTOPFILE="/home/nemo/.local/share/applications/"${APP[2]}".desktop"
    echo "[Desktop Entry]" > "$DESKTOPFILE"
    echo "Type=Application" >> "$DESKTOPFILE"
    echo "Name="${APP[0]} >> "$DESKTOPFILE"
    echo "Comment="${APP[1]} >> "$DESKTOPFILE"
    echo "Exec=flatpak-runner "${APP[2]} >> "$DESKTOPFILE"
done

**Comment by rinigus** [comment]
Desktop icons are now generated automatically on a when flatpak-runner is started without any arguments. Closing
