### ISSUE TITLE
Add desktop and icon for Flatpak Runner

### ISSUE THREAD

**Issue by rinigus** [sailfishos-flatpak/flatpak-runner#9]
As in future, Flatpak Runner could be used to setup environment variables and maybe few other functions, it needs to be placed in the application drawer. So, icon and .desktop files are needed.

**Comment by rinigus** [comment]
Location for .desktop files: ~/.local/share/applications

**Comment by ApostolosB** [comment]
![flatpack-runner](https://user-images.githubusercontent.com/13685565/71905106-24b28980-3170-11ea-8998-aa2e9d5493d0.png)

Icon for flatpack-runner

**Comment by rinigus** [comment]
Thank you. And we have SVG as well from you

**Comment by rinigus** [comment]
Fixed in febaa745077882c9f46bc1a935c66c9b9df812d0
